FFC-187745: Exception Event
DEFRA/ffc-ahwr-event pull request #15
Opened 2023-06-02 07:40 UTC by json-hamilton

https://dev.azure.com/defragovuk/DEFRA-FFC/_sprints/taskboard/DEFRA-FFC%20Vet%20Visits%20Team/DEFRA-FFC/Vet%20Visits/Sprint%2032?workitem=187745

2023-06-05 08:21 UTC, liamwilson-kainos requested changes

2023-06-05 08:21 UTC, liamwilson-kainos commented on ffc-ahwr-event/function.json
> +      "tableName": "ffcahwrexception",
I think we could call this `ffcahwrineligibility` to indicate it is not generic for all exceptions and it is more for capturing known cases where a business is not eligible

2023-06-05 08:21 UTC, liamwilson-kainos commented on ffc-ahwr-event/index.js
> +const onExceptionEvent = require('./exception-event')
as above maybe `onIneligibilityEvent`

2023-06-06 09:35 UTC, liamwilson-kainos approved these changes

2023-06-06 09:39 UTC, chrissmKainos approved these changes

2023-06-06 09:43 UTC, merged